using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ArrnowConstruct.Core.Exceptions
{
    public static class GlobalExceptions
    {
        public const string ClientDoessNotExistsExceptionMessage = "This client does not exist!";

        public const string RequestDoesNotExistExceptionMessage = "This request does not exist!";

        public const string ConstructorDoesNotExistExceptionMessage = "This constructor does not exist!";

        public const string ConstructorWithEmailDoesNotExistExceptionMessage = "This constructor does not exist!";

        public const string UserDoesNotExistExceptionMessage = "This user does not exist!";

        public const string PostDoesNotExistExceptionMessage = "This post does not exist!";

        public const string SiteDoesNotExistExceptionMessage = "This site does not exist!";

        public const string UsersDoNotExist = "There are no users yet.";

        public const string ClientsDoNotExist = "There are no clients yet.";

        public const string ConstructorsDoNotExist = "There are no constructors yet.";

        public const string PostsDoNotExist = "There are no posts yet.";

        public const string RequestsDoNotExist = "There are no requests yet.";

        public const string SitesDoNotExist = "There are no sites yet.";

        public const string RequestAlreadyRejected = "This Request has already been rejected.";

        public const string RequestAlreadyDeleted = "This Request has already been deleted.";

        public const string RequestAlreadyConfirmed = "This Request has already been confirmed.";

        public const string SiteCannotBeFinished = "This Site cannot be finished.";

        public const string SiteIsAlreadyDisactivated = "This Site is already disactivated.";


    }
}
